import type { TourEvent } from "@/lib/domain";

/** Fechas oficiales de gira (mock hasta conexión Bandsintown). */
export function getMockTourEvents(): TourEvent[] {
  return [
    {
      id: "tour-2026-04-10-maipu",
      artistName: "Jorge Drexler",
      city: "Maipú",
      countryCode: "AR",
      venue: "Arena Maipu Stadium",
      localDate: "2026-04-10",
      ticketUrl: "#",
      rsvpUrl: "#",
    },
    {
      id: "tour-2026-04-12-cordoba",
      artistName: "Jorge Drexler",
      city: "Córdoba",
      countryCode: "AR",
      venue: "QUALITY ARENA",
      localDate: "2026-04-12",
      ticketUrl: "#",
      rsvpUrl: "#",
    },
    {
      id: "tour-2026-04-14-rosario",
      artistName: "Jorge Drexler",
      city: "Rosario",
      countryCode: "AR",
      venue: "BIOCERES ARENA",
      localDate: "2026-04-14",
      ticketUrl: "#",
      rsvpUrl: "#",
    },
    {
      id: "tour-2026-04-17-buenosaires",
      artistName: "Jorge Drexler",
      city: "Buenos Aires",
      countryCode: "AR",
      venue: "Movistar Arena",
      localDate: "2026-04-17",
      ticketUrl: "#",
      rsvpUrl: "#",
    },
    {
      id: "tour-2026-04-18-buenosaires",
      artistName: "Jorge Drexler",
      city: "Buenos Aires",
      countryCode: "AR",
      venue: "Movistar Arena",
      localDate: "2026-04-18",
      ticketUrl: "#",
      rsvpUrl: "#",
    },
    {
      id: "tour-2026-04-21-mardelplata",
      artistName: "Jorge Drexler",
      city: "Mar del Plata",
      countryCode: "AR",
      venue: "Radio City Art Center Roxy Melany",
      localDate: "2026-04-21",
      ticketUrl: "#",
      rsvpUrl: "#",
    },
    {
      id: "tour-2026-04-25-santiago",
      artistName: "Jorge Drexler",
      city: "Santiago",
      countryCode: "CL",
      venue: "Movistar Arena",
      localDate: "2026-04-25",
      ticketUrl: "#",
      rsvpUrl: "#",
    },
    {
      id: "tour-2026-04-26-santiago",
      artistName: "Jorge Drexler",
      city: "Santiago",
      countryCode: "CL",
      venue: "Movistar Arena",
      localDate: "2026-04-26",
      ticketUrl: "#",
      rsvpUrl: "#",
    },
    {
      id: "tour-2026-05-23-saopaulo",
      artistName: "Jorge Drexler",
      city: "São Paulo",
      countryCode: "BR",
      venue: "Espaço Unimed",
      localDate: "2026-05-23",
      ticketUrl: "#",
      rsvpUrl: "#",
    },
    {
      id: "tour-2026-05-29-portoalegre",
      artistName: "Jorge Drexler",
      city: "Porto Alegre",
      countryCode: "BR",
      venue: "Araújo Vianna Auditorium",
      localDate: "2026-05-29",
      ticketUrl: "#",
      rsvpUrl: "#",
    },
    {
      id: "tour-2026-05-30-portoalegre",
      artistName: "Jorge Drexler",
      city: "Porto Alegre",
      countryCode: "BR",
      venue: "Araújo Vianna Auditorium",
      localDate: "2026-05-30",
      ticketUrl: "#",
      rsvpUrl: "#",
    },
    {
      id: "tour-2026-06-06-montevideo",
      artistName: "Jorge Drexler",
      city: "Montevideo",
      countryCode: "UY",
      venue: "Antel Arena",
      localDate: "2026-06-06",
      ticketUrl: "#",
      rsvpUrl: "#",
    },
    {
      id: "tour-2026-09-26-madrid",
      artistName: "Jorge Drexler",
      city: "Madrid",
      countryCode: "ES",
      venue: "Movistar Arena",
      localDate: "2026-09-26",
      ticketUrl: "#",
      rsvpUrl: "#",
    },
    {
      id: "tour-2026-10-16-valencia",
      artistName: "Jorge Drexler",
      city: "València",
      countryCode: "ES",
      venue: "Roig Arena",
      localDate: "2026-10-16",
      ticketUrl: "#",
      rsvpUrl: "#",
    },
    {
      id: "tour-2026-10-31-barcelona",
      artistName: "Jorge Drexler",
      city: "Barcelona",
      countryCode: "ES",
      venue: "Palau Sant Jordi",
      localDate: "2026-10-31",
      ticketUrl: "#",
      rsvpUrl: "#",
    },
  ];
}
